image: docker

before_script:
  - pip install mkdocs
  - pip install mkdocs-material mkdocstrings

# build mkdocs documentation
pages:
  image: docker
  script:
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master
  tags:
  - shared
  - docker
