image: python:3.7

before_script:
  - pip install mkdocs
  - pip install mkdocs-material mkdocstrings

# build mkdocs documentation
pages:
  image: python:3.7
  script:
  - pip install -e .
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master
  tags:
  - shared
  - docker
