site_name: asdc
site_description: automation tools for autonomous scanning droplet cell electrochemical characterization

nav:
  - Overview: "index.md"
  - SDC Reference:
    - "sdc client": "reference/client.md"
    - "automation client": "reference/controller.md"
    - microcontroller: "reference/microcontroller.md"
    - "syringe pumps": "reference/pumps.md"
  - Utilities:
    - webcam: "reference/webcam.md"
  - Experiments:
    - protocol: "experiment/protocol.md"
    - configuration: "experiment/config.md"

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      watch:
      - ./asdc

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg


extra_css:
  - custom.css