target_file: data/map.halfcombi.csv
data_dir:

# motion controller speed in m/s
speed: 1e-3

# use INTERNAL/EXTERNAL cell
cell: INTERNAL

# add a delay before running each experiment...
initial_delay: 0

# ease off vertically before moving the cell laterally
lift: True

# step height in meters
delta_z: 5e-3

# press down below vertical setpoint to reseat probe after lateral motion
compress: True
